[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AntiscammerAPI"
authors = [{name = "Antiscammer dev team", email = "Ryanmaicus313@gmail.com"}]
dynamic = ["version", "description"]
